In [80]:
print("HEllo World")

HEllo World


In [81]:
import numpy as np

In [82]:
arr = np.array([2,3,5,6,5])   # 1D array 
print(arr)
print(type(arr))
print(arr.shape)

[2 3 5 6 5]
<class 'numpy.ndarray'>
(5,)


In [83]:
arr = arr.reshape(1,5)
print(arr.shape)
print(arr)

(1, 5)
[[2 3 5 6 5]]


In [84]:
arr = np.array([
    [1,2,2,3,5,],
    [25,5,55,6,5]
])

In [85]:
print(arr.shape)

(2, 5)


In [86]:
arrOnes = np.ones((2,3))
print(arrOnes)

[[1. 1. 1.]
 [1. 1. 1.]]


In [87]:
## Identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
print(arrOnes.dtype)
arrOnes = arrOnes.astype(int)
print(arrOnes)
print(arrOnes.dtype)

float64
[[1 1 1]
 [1 1 1]]
int64


In [89]:
## Numpy Vectorized Operations 


arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [90]:
## universal Functions -> That apply to all the elements 

print(np.square(arr1))
print(np.exp(arr1))
print(np.log(arr1))
print(np.cos(arr1))

[ 1  4  9 16 25]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [91]:
arr = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [5,2,6,9]
])
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [5 2 6 9]]


In [92]:
arr[0][0]

np.int64(1)

In [93]:
print(arr[1:,2:])   ## Slicing Of rows and columns 

[[7 8]
 [6 9]]


In [94]:
## Modify the array elements 

arr[0][0] = 100
print(arr)
arr[:,2:] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  5   2   6   9]]
[[100   2 100 100]
 [  5   6 100 100]
 [  5   2 100 100]]


In [96]:
#stasticial - Normalization 

## TO have mean = 0, and standarad deviation  of 1 


data = np.array([5,6,79,33,2,1,55,1,2,5,1,5])

mean = np.mean(data)
stdDev = np.std(data)

normalizedData = (data - mean) / stdDev

print(normalizedData)
print(int(normalizedData.mean()))

[-0.45586521 -0.41534386  2.54271483  0.67873264 -0.57742926 -0.61795062
  1.57020238 -0.61795062 -0.57742926 -0.45586521 -0.61795062 -0.45586521]
0


In [97]:
#
print(np.mean(data))
print(np.median(data))
print(np.var(data))
print(np.std(data))

16.25
5.0
609.0208333333334
24.678347459530862


In [105]:
## Logical Operations 

data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data)

dataConditioned = data[(data>=5) & (data <= 8)]
print(dataConditioned)

[ 1  2  3  4  5  6  7  8  9 10]
[5 6 7 8]
