In [1]:
import numpy as np

In [6]:
arr = np.array(np.random.randint(1,20,size=25))
arr = arr.reshape(5,5)
arr

array([[ 9,  6, 18,  8,  2],
       [ 6, 11,  4, 13,  9],
       [11, 17,  9,  6,  9],
       [ 2, 10, 19, 14,  1],
       [ 3,  8, 19,  6,  2]], dtype=int32)

In [8]:
arr[:,2] = 1

arr

array([[ 9,  6,  1,  8,  2],
       [ 6, 11,  1, 13,  9],
       [11, 17,  1,  6,  9],
       [ 2, 10,  1, 14,  1],
       [ 3,  8,  1,  6,  2]], dtype=int32)

In [11]:
arr = np.array([x for x in range(1,17)])
arr = arr.reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
np.fill_diagonal(arr, 0)
arr

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

In [15]:
arr = np.array([x for x in range(1,37)])
arr = arr.reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [17]:
arrExtracted = arr[3:6, 2:5]
arrExtracted

array([[21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

In [18]:
arr = np.array([x for x in range(1,17)])
arr = arr.reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
arr.sum(axis=0)

array([28, 32, 36, 40])

In [21]:
arr.sum(axis=1)

array([10, 26, 42, 58])

In [29]:
arr = np.array(np.random.randint(0,100,25))
arr = arr.reshape(5,5)
arr

array([[ 3, 78, 36, 43,  1],
       [63, 12, 17,  3, 67],
       [92, 92, 89, 23,  3],
       [78, 68, 38, 71,  8],
       [76, 42, 58, 23, 84]], dtype=int32)

In [34]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

46.72
43.0
31.434401537169435
988.1216000000001


In [35]:
arr = np.array([x for x in range(1,10)])
arr = arr.reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
meanValue = np.mean(arr)
stdDevValue = np.std(arr)

nor = (meanValue - arr) / stdDevValue
nor

array([[ 1.54919334,  1.161895  ,  0.77459667],
       [ 0.38729833,  0.        , -0.38729833],
       [-0.77459667, -1.161895  , -1.54919334]])

In [38]:
arr = np.array(np.random.randint(0,100,size=9))
arr = arr.reshape(3,3)
arr

array([[55, 59, 13],
       [57, 21, 64],
       [36, 83, 25]], dtype=int32)

In [39]:
np.linalg.det(arr)

np.float64(-159749.00000000017)

In [41]:
np.linalg.eigvals(arr)

array([136.93887078,  20.62424577, -56.56311656])

In [42]:
np.linalg.inv(arr)

array([[ 0.02996576,  0.00247889, -0.02192815],
       [-0.00550238, -0.00567766,  0.01739604],
       [-0.02488278,  0.01528022,  0.01382168]])

In [43]:
arr = np.array(np.random.randint(0, 20, size = 16)).reshape(4,4)
arr


array([[ 2, 12, 13,  8],
       [ 7,  8, 14, 12],
       [ 3, 16,  3,  1],
       [14,  7, 13, 10]], dtype=int32)

In [46]:
arr[arr > 10] = 10
arr

array([[ 2, 10, 10,  8],
       [ 7,  8, 10, 10],
       [ 3, 10,  3,  1],
       [10,  7, 10, 10]], dtype=int32)

In [51]:
data = {
    'name' : ['Aashish', 'Aarunee', 'Aditya'],
    'age' : [25,45,25],
    'weight' : [123, 223, 33]
}

arr = np.array(list(data.values()))
arr.sort(axis=1)
arr

array([['Aarunee', 'Aashish', 'Aditya'],
       ['25', '25', '45'],
       ['123', '223', '33']], dtype='<U21')